name: Test

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm test
      - run: npm ci
        working-directory: auth
      - run: npm run types && npm run check && npm test
        working-directory: auth
      - run: npx playwright install --with-deps chromium --only-shell
        working-directory: auth
      - run: npm run test:browser && npm audit --audit-level=high
        working-directory: auth
